### ISSUE TITLE
Reset button lights when fan is turned off manually

### ISSUE THREAD

**Issue by gminco** [sdwilsh/ha-zen32-exhaust-fan-blueprint#13]
To reproduce:
Press the top left button, after a minute, press the big button to turn the fan off.
The fan turns off and the light goes back to blue on the big button, but the top left button's light remains on.

**Comment by sdwilsh** [comment]
I'm traveling and won't be home for a week to check on this.  I will say I did hit some weird issues where sometimes lights didn't change, but the service was called.  This seems to correlate with sending too many commands, and unfortunately there's no way to get the property to verify it worked.

I might need to patch home assistant to properly fix this, if that is the underlying problem.

**Comment by sdwilsh** [comment]
I'm finally getting back to this.  I can reproduce the issue, and I'll work on a fix for it tonight.  I know you [posted a workaround for this](https://community.home-assistant.io/t/zooz-zen32-scene-controller-for-timed-exhaust-fan-control/452275/6), but I'd like to fix it so people don't need to do that.

**Comment by sdwilsh** [comment]
For my own context, the problem is that the off state is getting canceled before it can complete:
![image](https://github.com/sdwilsh/ha-zen32-exhaust-fan-blueprint/assets/656602/b58eb5f1-2d30-46cd-9004-d7969a76be73)
This comes in when pressing the off button:
```
platform: event
event_type: zwave_js_value_notification
event_data:
  device_id: ...
  property: scene
  property_key: '005'
id: zwave_scene_60m
```
